title: Brute Force Attack Detection
id: 1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p
status: stable
description: Detects multiple failed login attempts indicating a brute force attack
author: ThreatOps SOC Team
date: 2024/01/01
level: high
tags:
    - attack.credential_access
    - attack.t1110
    - attack.t1110.001
references:
    - https://attack.mitre.org/techniques/T1110/
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4625
    condition: selection
falsepositives:
    - User forgot password
    - Account lockout policy testing

