title: Credential Dumping Tool Execution
id: 5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t
status: stable
description: Detects execution of known credential dumping tools like Mimikatz
author: ThreatOps SOC Team
date: 2024/01/01
level: critical
tags:
    - attack.credential_access
    - attack.t1003
    - attack.t1003.001
references:
    - https://attack.mitre.org/techniques/T1003/
logsource:
    product: windows
    category: process_creation
detection:
    selection_tools:
        Image|contains:
            - 'mimikatz'
            - 'procdump'
            - 'pwdump'
            - 'gsecdump'
            - 'wce.exe'
    selection_lsass:
        CommandLine|contains:
            - 'lsass'
            - 'sekurlsa'
    condition: selection_tools or selection_lsass
falsepositives:
    - Security testing with proper authorization
    - Penetration testing

