title: Lateral Movement via SMB/RPC
id: 4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s
status: experimental
description: Detects potential lateral movement using SMB or RPC connections
author: ThreatOps SOC Team
date: 2024/01/01
level: high
tags:
    - attack.lateral_movement
    - attack.t1021.002
    - attack.t1021
references:
    - https://attack.mitre.org/techniques/T1021/002/
logsource:
    product: windows
    category: network_connection
detection:
    selection:
        DestinationPort:
            - 445
            - 139
            - 135
        ProcessName|endswith:
            - '\psexec.exe'
            - '\wmic.exe'
            - '\powershell.exe'
            - '\cmd.exe'
    condition: selection
falsepositives:
    - Legitimate administrative tasks
    - System management tools
    - Backup solutions

