title: PowerShell Encoded Command Execution
id: 3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r
status: stable
description: Detects PowerShell execution with encoded commands (often used by attackers)
author: ThreatOps SOC Team
date: 2024/01/01
level: high
tags:
    - attack.execution
    - attack.t1059.001
    - attack.defense_evasion
    - attack.t1027
references:
    - https://attack.mitre.org/techniques/T1059/001/
    - https://attack.mitre.org/techniques/T1027/
logsource:
    product: windows
    category: process_creation
detection:
    selection_process:
        Image|endswith: 
            - '\powershell.exe'
            - '\pwsh.exe'
    selection_encoded:
        CommandLine|contains:
            - ' -enc '
            - ' -encoded '
            - ' -EncodedCommand '
            - ' -e '
    condition: selection_process and selection_encoded
falsepositives:
    - Legitimate administrative scripts
    - Software deployment tools

