title: Suspicious Privilege Escalation
id: 2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q
status: stable
description: Detects suspicious privilege escalation attempts by non-privileged users
author: ThreatOps SOC Team
date: 2024/01/01
level: critical
tags:
    - attack.privilege_escalation
    - attack.t1078
    - attack.t1068
references:
    - https://attack.mitre.org/techniques/T1078/
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4672
    filter:
        User:
            - SYSTEM
            - Administrator
            - root
    condition: selection and not filter
falsepositives:
    - Legitimate administrative activities
    - Service account operations

